### ISSUE TITLE
Exception when trying to apply

### ISSUE THREAD

**Issue by Vampire** [jonnyzzz/gradle-java9c#2] opened 2018-03-06 18:09 UTC
```
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property ext has not been initialized
        at org.jonnyzzz.gradle.java9c.ScanClasspathTask.getExt(java9c.kt:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
        at org.jonnyzzz.gradle.java9c.ScanClasspathTask_Decorated.getProperty(Unknown Source)
        at net.saliman.gradle.plugin.properties.PropertiesPlugin$_registerTaskListener_closure6.doCall(PropertiesPlugin.groovy:440)
        at jdk.internal.reflect.GeneratedMethodAccessor580.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:136)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:642)
        at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:90)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.internal.ImmutableActionSet$CompositeSet.execute(ImmutableActionSet.java:196)
        at org.gradle.internal.MutableActionSet.execute(MutableActionSet.java:35)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:204)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:198)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:93)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.addTask(DefaultTaskContainer.java:101)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:120)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:150)
        at org.jonnyzzz.gradle.java9c.GradlePlugin$apply$1.execute(java9c.kt:45)
        at org.jonnyzzz.gradle.java9c.GradlePlugin$apply$1.execute(java9c.kt:28)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
        at org.jonnyzzz.gradle.java9c.GradlePlugin.apply(java9c.kt:39)
        at org.jonnyzzz.gradle.java9c.GradlePlugin.apply(java9c.kt:28)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:164)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
        ... 140 more
```

**Comment by Vampire** [comment] 2018-03-06 18:09
This is with Gradle 4.6

**Comment by jonnyzzz** [comment] 2018-03-11 22:26
Hello,

I see the strange line over here

        at org.jonnyzzz.gradle.java9c.ScanClasspathTask_Decorated.getProperty(Unknown
Source)
        at net.saliman.gradle.plugin.properties.PropertiesPlugin$_registerTaskListener_closure6.doCall(PropertiesPlugin.groovy:440)

It looks like the PropertiesPlugin attempts reading all object fields, even
fields that are marked as @Internal. Could
you please provide a minimalistic example for me to include it to unit
tests.

I've added a test with "net.saliman.properties" and it failed with a
similar exception. It looks like the properties plugin issue, as it
attempts to run nasty reflexive/groovy calls to the task of the java9c
plugin. Please find the test in master branch to reproduce the
problem org.jonnyzzz.gradle.java9c.IntegrationTest_4_4_1#test_properties_plugin

**Comment by Vampire** [comment] 2018-03-12 10:25
I don't think you are right.
The properties plugin code at the relevant position is.
```java
task.ext.requiredProperty = { String propertyName ->
	project.gradle.taskGraph.whenReady { graph ->
		if (graph.hasTask(task.path)) {
			checkProperty(project, propertyName, task, "requiredProperty")
		}
	}
}
```
Line 440 is the first line.
This means it tries to set an `ext` property on your task.
Quoted from the Gradke userguide:
```
All enhanced objects in Gradle’s domain model can hold extra user-defined properties.
This includes, but is not limited to, projects, tasks, and source sets.
Extra properties can be added, read and set via the owning object’s ext property.
Alternatively, an ext block can be used to add multiple properties at once.
```
So this should work just fine.

**Comment by Vampire** [comment] 2018-03-12 10:28
From a quick look at your code it seems more like you are overwriting the `ext` property with something own and that should never be done.

**Closed as completed** 2018-03-12 16:59 UTC

**Comment by jonnyzzz** [comment] 2018-03-12 17:08
Oh, thanks for the tip. I missed the point my `ext` field was interfering Gradle internals. Fixed it now. 
Please try `0.2.3` version with the fix.
